[package]
name = "obscure-resurrection"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bevy = { version = "0.6.1", features = ["dynamic"] }
bevy = "0.6.1"
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
bevy_ecs_ldtk = "0.1.0"
heron = { version = "1.1.0", features = ["2d"] }
wasm-bindgen = "0.2.79"
